services:
  mariadb-parcial:
    image: mariadb:11.1
    container_name: mariadb-parcial
    environment:
      MARIADB_DATABASE: universidad_db
      MARIADB_USER: springuser
      MARIADB_PASSWORD: springpass
      MARIADB_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb", "-h", "127.0.0.1", "-uroot", "-prootpass", "-e", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  crud-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jessikaguti/jsuazag:latest
    container_name: crud-app
    depends_on:
      mariadb-parcial:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:

volumes:
  mariadb_data: